name: ZAP DAST (Baseline)

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  issues: write

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install app deps
        run: |
          python -m pip install --upgrade pip
          pip install -r Requirements.txt
          pip install flask-sqlalchemy

      - name: Run Flask app (background)
        run: |
          nohup python secure_API/file1.py > flask.log 2>&1 &
          echo "Started Flask, waiting..."
          for i in {1..30}; do
            curl -sSf http://127.0.0.1:5000/ > /dev/null && break
            sleep 2
          done
          curl -sSf http://127.0.0.1:5000/ > /dev/null

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://127.0.0.1:5000/"
          cmd_options: "-a -m 2"

      - name: Upload ZAP reports + server log
        uses: actions/upload-artifact@v4
        with:
          name: dast-zap-report
          path: |
            report_html.html
            report_json.json
            report_md.md
            flask.log
